### ISSUE TITLE
Use oe_authentication with Drupal 9 

### ISSUE THREAD

**Issue by giorgosbotis** [openeuropa/oe_authentication#125]
Hello,
I can see that a Drupal 8 core version is required for this module to install with composer.  Will there be any Drupal 9 version of this module?

Thank you,
gb

**Comment by alesrebec** [comment]
The Drupal 9 compatibility is in the works now.
https://github.com/openeuropa/oe_authentication/commit/6946e5e4db5b2c5269c1ae7a5d74718690f41c6f#diff-f22b3c5f872d3bc6e33a2562b9ece2934f2b86ac8ac7c6173bdf81a5892d7b6c

**Comment by brummbar** [comment]
Fixed by #132 .
