### ISSUE TITLE
New release plan

### ISSUE THREAD

**Issue by alesrebec** [openeuropa/oe_authentication#134]
The last official release (1.3.0) is now more than a year old and the CAS version is requesting an update which is updated in version 1.4.0 that is in an own branch but hasn't been released to be picked up by composer require as instructed (composer require openeuropa/oe_authentication)

![Screenshot from 2021-07-08 15-31-53](https://user-images.githubusercontent.com/426177/124930603-c3d46d80-e001-11eb-87c1-3c3859321c2f.png)

![Screenshot from 2021-07-08 15-32-07](https://user-images.githubusercontent.com/426177/124930623-c8008b00-e001-11eb-9e3f-db106fdbfebd.png)

Are there plans to release the next version?

**Comment by brummbar** [comment]
Fixed by #132 .
