### ISSUE TITLE
Compatibility with symfony/http-foundation v4.4.44

### ISSUE THREAD

**Issue by maggie-drupal** [openeuropa/oe_authentication#164]
Cannot be installed with current latest Drupal 9 version.
Please update to be compatible with symfony/http-foundation v4.4.44

 - openeuropa/oe_authentication 1.8.0 requires symfony/http-foundation <=4.4.41 
 - latest drupal 9 version of symfony is v4.4.44

**Comment by brummbar** [comment]
The problem occurs when using drupal/core 9.5.x and the drupal/core-recommended package.

**Comment by maggie-drupal** [comment]
Drupal 9.3 security support ends in three months. Is there a timeline on when oe_authentication will be able to support >9.3?
