### ISSUE TITLE
Replace heavy, proprietary mock CAS server with a lightweight and open source solution

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/oe_authentication#57]
When I follow the instructions I get an error regarding missing credentials when docker-compose attempts to download the `authentication` container:

```
$ docker-compose pull
Pulling web            ... done
Pulling mysql          ... done
Pulling selenium       ... done
Pulling authentication ... error

ERROR: for authentication  b'Get https://registry.fpfis.tech.ec.europa.eu/v2/ecas-mock-server/manifests/4.6.0: no basic auth credentials'
ERROR: Get https://registry.fpfis.tech.ec.europa.eu/v2/ecas-mock-server/manifests/4.6.0: no basic auth credentials
```

Can a container be made that mocks the service using open source software so that it can be made publicly accessible? There are many tools available that can be used to easily mock a REST or SOAP service.

**Comment by dxvargas** [comment]
@pfrenssen indeed a docker login is required, as stated in [README.md](https://github.com/openeuropa/oe_authentication/blob/master/README.md):

> The container docker that provides the EULogin Mock Service ecas-mock-server:4.6.0 is available on a private repo registry.fpfis.tech.ec.europa.eu

We've already used a generic cas service ([pcas](https://github.com/openeuropa/pcas)) but it wasn't enough because some features were missing and also ecas/eulogin as some specific behavior.

With current docker container we have exactly what we need with the advantage that it is maintained by EC/DIGIT/EULogin team.

To change again to another container we would need an analysis with pros and cons for the candidate. It's a decision that business should also take part, so I suggest the discussion should occur in our collaborative tool.

**Comment by pfrenssen** [comment]
I have made a mock CAS server which is open source and has a footprint that is more than 25000x smaller than the one from ecas: https://www.drupal.org/project/cas_mock_server

I took care to make it as close as possible to the needs of oe_authentication, but it is adhering to the CAS specification. I also provided Behat integration, and have used the tests from this component as a blueprint. The UI strings are configurable so they can be adapted to look exactly like EU Login. This should make it possible to switch to this mock server with minimal effort.

Here is the Behat test coverage for it: https://git.drupalcode.org/project/cas_mock_server/blob/8.x-1.x/tests/features/login.feature

**Comment by verbruggenalex** [comment]
I'm trying to use the cas_mock_server for testing the oe_authentication module. But I'm unable to get it correctly configured. @pfrenssen do you have a bit more information on how to configure oe_authentication together with cas_mock_server?

**Comment by pfrenssen** [comment]
@verbruggenalex thanks for giving it a shot! I have added documentation on how to set it up in the README file: https://git.drupalcode.org/project/cas_mock_server/blob/8.x-1.x/README.md

What is it exactly that is not working? Please note that you need to manually start the mock server using a Drush command.

The module is also designed to work with the Drupal CAS module, but this is also used by oe_authentication, so I expect it to work.

The mock server works by accesses the CAS module's endpoint and sending it requests that are similar to the ones sent by a real CAS service.

**Comment by verbruggenalex** [comment]
First problem was that I was using the 0.x version of this module. Which didn't work at all.

Finally got it to work with the oe_authentication module. It seemed that I forgot to change the server path to point to the mock server:
```
$config['cas.settings']['server']['hostname'] = 'web';
$config['cas.settings']['server']['port'] = '8080';
$config['cas.settings']['server']['path'] = '/web/cas-mock-server';
```

I think this is a good alternative for logging in with eulogin locally and for testing. Much better than the bloated private image that has licensing issues.

**Comment by brummbar** [comment]
We have a mock server now.
