### ISSUE TITLE
Fix Drupal core lazy sessions issue

### ISSUE THREAD

**Issue by imanoleguskiza** [openeuropa/oe_authentication#60]
After the latest symfony/http-foundation 3.4.24 update Drupal core has reported an issue with its lazy sessions: https://www.drupal.org/project/drupal/issues/3045349

The current solution is to fix the http-foundation version in te composer.json file:

`"conflict": {
        "symfony/http-foundation": "3.4.24"
    },`

**Comment by dxvargas** [comment]
It's fixed in `drupal/core:8.6.14` so we need to use it when using `symfony/http-foundation": "3.4.24`.

**Comment by dxvargas** [comment]
Fixed with new release `drupal-core-require-dev:8.6.14`.
