### ISSUE TITLE
missing modules oe_authentication

### ISSUE THREAD

**Issue by benjamin-dittwald** [openeuropa/oe_authentication#77]
When following the installation instructions we fail when enabling the module in a Drupal 8 installation.

```bash
$ composer require  openeuropa/pcas
Using version ^0.2.2 for openeuropa/pcas
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package openeuropa/pcas is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
$ composer require openeuropa/oe_authentication
Using version ^0.5.0 for openeuropa/oe_authentication
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package openeuropa/pcas is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
$ drush en oe_authentication
 
In PmCommands.php line 247:
 
  Unable to install modules oe_authentication due to missing modules oe_authentication.
 
 
pm:enable [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command> [<modules>]...
```

Do you have any idea what is going wrong?

Best
Ben

**Comment by upchuk** [comment]
@benjamin-dittwald Hey there, thanks for reporting the issue. Can you please point me to the installation instructions you mention? 

We are no longer using/depending on the openeuropa/pcas library so this should not be an issue.

Thanks

**Comment by benjamin-dittwald** [comment]
Hi @upchuk thanks for the reply! We used [this install instruction](https://github.com/openeuropa/oe_authentication/blob/master/README.md).

When issueing

```bash
$ composer require openeuropa/oe_authentication
```

pcas gets mentioned as unavailable, so we tried to install it manually.

**Comment by brummbar** [comment]
Hi @benjamin-dittwald, what is the [minimum stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) specified in your composer.json?
It could be that is "stable", so it uses version 0.5.0 of oe_authentication.
Can you try to do `composer require openeuropa/oe_authentication:^1.0.0@beta`?
If it doesn't work, post the result of:
```
composer why openeuropa/oe_authentication
```
Thanks in advance.

**Comment by benjamin-dittwald** [comment]
Hi @brummbar, thanks. We had  `"minimum-stability": "dev"`. After we changed to what you proposed, the installation went through without any other issues.

Thanks a lot! :)

**Comment by brummbar** [comment]
Perfect! I'll close this issue then. Have a nice day!
