### ISSUE TITLE
Don't create and map user fields. Use cas_attributes instead

### ISSUE THREAD

**Issue by claudiu-cristea** [openeuropa/oe_authentication#81]
When installed, the module creates next base fields for the `user` entity: `field_oe_firstname`, `field_oe_lastname`, `field_oe_department`, `field_oe_organisation`. Also, on registering a new Drupal account with data taken from EU Login, it fills those fields with data.

This approach is hard coupled to a specific OE business model, preventing module reusability. The module should not be in business of configuring the `user` entity fields. That should be deferred to other module, to the parent project or to configuration management (if the fields are converted from base to configurable).

Also there's no way to allow users change data on the site, e.g family name, because everytime they are logging in, data from EU Login is overwriting the local changes.

### Proposal

* Stop adding `user` base fields.
* Use `cas_attributes` module to map and set fields.

**Comment by claudiu-cristea** [comment]
We'll move the base fields and setting attribute > fields into a submodule. In the future, the fields could be changed into configurable fields and `cas_attributes` could be used to set the values.

**Comment by brummbar** [comment]
Awesome, we'll take care in the future to introduce `cas_attributes`.
