### ISSUE TITLE
Replace master branch with 8.x-1.x

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/oe_authentication#91]
Since this is a Drupal 8 module, we should use the branch naming conventions as documented on drupal.org. We should switch to `8.x-1.x` and empty the master branch, leaving a note in the README directing the users to the correct branch to use.

Ref. [Maintaining a Drupal project with Git: Working with branches and tags](https://www.drupal.org/node/711070#branches-tags)

**Comment by ademarco** [comment]
We are not gonna adopt Drupal.org conventions on OpenEuropa components as:

1. They are not hosted on Drupal.org, so we don't have to follow its conventions
2. We need to have a proper semantic versioning in place, which d.o versioning model does not yet allow
